# Site settings
title: honger05
email: honger05@126.com
description: > # this means to ignore newlines until "baseurl:"
  你听好了，我从来不抖机灵yo.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.honger05.com" # the base hostname & protocol for your site
github_username:  honger05

# Build settings [ rdiscount | kramdown | redcarpet ]
markdown: redcarpet

highlighter: pygments


